name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: create .env file
        run: |
          echo "PORT=${{ secrets.PORT }}" > .env
          echo "MONGO_URL=${{ secrets.MONGO_URL }}" >> .env
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" >> .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "CLOUD_NAME=${{ secrets.CLOUD_NAME }}" >> .env
          echo "CLOUD_KEY=${{ secrets.CLOUD_KEY }}" >> .env
          echo "CLOUD_SECRET=${{ secrets.CLOUD_SECRET }}" >> .env
          echo "vnp_TmnCode=${{ secrets.vnp_TmnCode }}" >> .env
          echo "vnp_HashSecret=${{ secrets.vnp_HashSecret }}" >> .env
          echo "vnp_Url=${{ secrets.vnp_Url }}" >> .env
          echo "vnp_ReturnUrl=${{ secrets.vnp_ReturnUrl }}" >> .env
      - run: pm2 restart tuxtax-backend